### PR TITLE
Expose metrics via JMX

### PR DESCRIPTION
**Pull request by ksauzz**
This PR exposes Retz's metrics via JMX.
In my understanding, most Java users collect JVM's metrics via JMX, so exposing metrics to JMX is useful.

I was not sure which package is suitable for adapter classes and its util class. I put them to `jmx` package for now, even though a jmx related class (AdminConsole) is located in `scheduler` package.

### CODE REVIEW

**Comment by ksauzz** [comment]
It seems some refactoring is needed for unifying JMX related tests. Will do.

**Comment by kuenishi** [comment]
After rerun all tests has passed. Is this still WIP?

**Comment by ksauzz** [comment]
Thanks! 😃  It's no longer WIP.　I just investigated a prop test fails.

**Comment by kuenishi** [comment]
As this conflicted with #178 I merged this manually and pushed to master with 1e6fa691e .

**Pull request merged**
