### PR TITLE
Handle errors appropriately

### PR DESCRIPTION
**Pull request by dtaniwaki**
Throwing `IOException` in Spark route doesn't make a good error response and clients don't know how to handle it.

So I made the following changes.

- Remove error hiding in client
- Define the base class of Retz server error
- Return `"Internal Server Error"` for other exceptions

### CODE REVIEW

**Comment by kuenishi** [comment]
Thank you for suggesting change, but I have several comments on this before going detail. First, please rebase these changes onto latest master which has your #148 merged.

Second, I agree that error response must be improved, but I don't think base class of server side errors needed. Sparkjava is smart enough that allows exception class matching like this:

```java
   exception(JobNotFoundException.class, (e, req, res) -> "some 404 response");
   exception(SomeOtherException.class, (e, req, res) -> "....");
   exception(IOException.class, (e, req, res) -> { /* error handling code */ ... } );
   exception(Exception.class, (e, req, res) -> "some 500 response");
```
I was so lazy and I didn't use that style instead, but this is the intended usage of Spark-java I want to follow it.

**Comment by dtaniwaki** [comment]
Thank you for your comment. I'll resolve the conflicts.

If you don't define custom exception, the exception handler has to expose actual message of `IOException` like this. Do you accept it? If so, I'll put an exception handler for each exception.

**Comment by dtaniwaki** [comment]
Of course, you can write `if/else` condition in exception handlers. I just felt it doesn't make a good readability.

**Comment by dtaniwaki** [comment]
I removed `RetzServerException` because I don't have to identify the error message on the client side for now. I don't know if we should directly expose `IOException`'s error message to clients. @kuenishi What do you think?

**Comment by kuenishi** [comment]
Generally speaking server side internal errors had better not be exposed to clients, but this case is a bit different; sandbox files are owned by users and errors due to sandbox files may deserve disclosure as messages. Also as a young software like this may want any tiny detailed information to diagnose any issues.

**Comment by dtaniwaki** [comment]
@kuenishi I updated the code with separated exception handlers. Is this something you expected? If not, I will fix it again.

**Comment by kuenishi** [comment]
Great job! Thanks again for your contribution.

**Pull request merged**
