### PR TITLE
Handle unexisting mesos files as 404

### PR DESCRIPTION
**Pull request by dtaniwaki**
Is it good idea to handle unexisting mesos file as 404 to Retz client?

### CODE REVIEW

**Comment by kuenishi** [comment]
Yes, it's a very good idea. But I'd like just handling `FileNotFoundException` as 404 in `exception()`, passing reason as String via FileNotFoundException constructor, rather than creating a new Exception class.

**Comment by dtaniwaki** [comment]
I made it like so. Could you review it again?

**Comment by dtaniwaki** [comment]
I recommited the change because my GPG signing key was not correct for some reason.

**Comment by kuenishi** [comment]
Thank you for contribution. I squashed your commits as it includes unnecessary code changes.

**Pull request merged**
