### PR TITLE
Replace unknown error

### PR DESCRIPTION
**Pull request by dtaniwaki**
Currently Retz client returns [`UnknownError`](https://docs.oracle.com/javase/8/docs/api/java/lang/UnknownError.html) for unknown error responses from the server.
I found `UnknownError` derives from `VirtualMachineError` and it's a fatal error.

I think we should not throw a fatal error for unknown server responses. So I created a general client error class along with a server side error class.

Could you consider merging this or consider some better error handling?

### CODE REVIEW

**Comment by kuenishi** [comment]
I see `UnknownError` is not to be used here. But is there any rationale adding parent classes that stand for client errors and server errors?

If those errors are to be sent through wire and needs abstraction on either side, they must have Jackson annotation like `protocol.data.Request` and `protocol.data.Response` .

**Comment by kuenishi** [comment]
Also, it is not right to use the name `Error` for exceptions, as described in [Java documents](http://docs.oracle.com/javase/specs/jls/se8/html/jls-11.html#jls-11.1.1) .

**Comment by dtaniwaki** [comment]
I made it simple so it returns `UnknownServerResponseException` without generalizing anything.

**Comment by dtaniwaki** [comment]
I recommited the change because my GPG signing key was not correct for some reason.

**Comment by kuenishi** [comment]
Thank you for your contribution! Besides, I squashed your commits to avoid unnecessary code logs although you signed your commits.

**Comment by dtaniwaki** [comment]
It's ok as long as the error has been fixed. By the way, I could've squashed it on my side after you reviewed.

**Pull request merged**
